openapi: 3.0.3
info:
  title: MoEngage Email Template API
  version: '2.0'
  description: |
    API for creating, updating, and searching Email templates within the MoEngage platform.
    
    **Postman Collections**
    We have made it easy for you to test the APIs. [View in Postman](https://www.postman.com/moengage-dev/workspace/api-docs/collection/3182294-c13b39d2-6abb-45a2-9f9f-312e52a65791?action=share&creator=3182294).
servers:
  - url: 'https://api-{dc}.moengage.com/v2'
    description: MoEngage Email Template API Server
    variables:
      dc:
        default: '01'
        description: 'Your MoEngage Data Center (DC). Refer to MoEngage docs for your correct DC.'
        enum:
          - '01'
          - '02'
          - '03'
          - '04'
security:
  - basicAuth: []
tags:
  - name: Email Templates
    description: Operations to manage email templates.

paths:
  /email-templates:
    post:
      tags:
        - Email Templates
      summary: Create Email Template
      description: |
        The Create Email Template API can be used to create an email template in MoEngage. This API helps you upload templates created outside the MoEngage ecosystem to MoEngage and use them for campaign creation on the MoEngage Dashboard.
      x-mint:
        content: |
          <Note>
          **Note**
          Templates created using this API cannot be used in the Drag and Drop Editor in the MoEngage Dashboard. They are supported only for the Custom HTML Editor (Froala Editor).
          </Note>

          # Rate Limit
          The rate limits are at the app level, and a maximum of **1000** (sum of all the API requests per app) requests are allowed for an app per minute.

          # FAQs
          <AccordionGroup>
            <Accordion title="How do I access templates created using this API on the MoEngage Dashboard?">
              You can access templates created using the Create Email Template API in the My Saved Templates tab during the second step of campaign creation in the MoEngage Dashboard.
            </Accordion>
          </AccordionGroup>
      operationId: createEmailTemplate
      parameters:
        - name: MOE-APPKEY
          in: header
          required: true
          description: |
            This is your MoEngage account's APP ID that has to be passed along with the request. 
            You can find your MoEngage APP ID at **Settings -> Account -> APIs -> App ID**.
          schema:
            type: string
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            default: application/json
          description: Set the Content-Type header to application/json.
      requestBody:
        required: true
        description: The details of the email template to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmailTemplateRequest'
      responses:
        '200':
          description: Request processed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSuccessResponse'
              example:
                status: success
                data:
                  id: 63f4962d4d31f4c68d980a01
                  msg: Custom email template saved
        '400':
          description: Bad Request (Validation failure, missing fields).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidHeader:
                  summary: Invalid Request Body/Header
                  value:
                    status: error
                    data:
                      code: 400
                      title: Invalid request body
                      description: MOE-APPKEY header is invalid or empty
                emptyName:
                  summary: Empty Name
                  value:
                    status: error
                    data:
                      code: 400
                      title: Invalid email name
                      description: Name field is empty
                emptyHtml:
                  summary: Empty HTML
                  value:
                    status: error
                    data:
                      code: 400
                      title: Invalid email body
                      description: Email body should not be empty
        '401':
          description: Authentication Failure.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                data:
                  code: 401
                  title: Authentication required
                  description: Invalid APP_ID used in Authentication Header
        '429':
          description: Rate Limit Breach.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: error
                data:
                  code: 429
                  title: rate limiter exception
                  description: Exceeded rate limit for this app
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                type: object
              example:
                title: Internal Server Error
                message: An unexpected error was encountered while processing this request. Please contact MoEngage Team

    get:
      tags:
        - Email Templates
      summary: Get All Email Templates
      description: The Get All Templates API fetches the list of all the email templates available in your MoEngage account.
      x-mint:
        content: |
          # Rate Limit
          The rate limits are at the app level, and a maximum of **1000** (sum of all the API requests per app) requests are allowed for an app per minute.
      operationId: getAllEmailTemplates
      parameters:
        - name: MOE-APPKEY
          in: header
          required: true
          description: |
            This is your MoEngage account's WORKSPACE ID which must be passed along with the request.
            You can find your MoEngage WORKSPACE ID at **Settings -> Account -> APIs -> Workspace ID**.
          schema:
            type: string
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            default: application/json
          description: Set the Content-Type header to application/json.
        - name: page
          in: query
          required: true
          description: |
            This parameter represents the page number. If this value is not specified, it will be considered as one by default.
            Each page will have a batch size of 20 (20 templates will be returned in a page).
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Successfully retrieved the list of templates.
          content:
            application/json: